version: '2'

services:
  consul:
    image: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net

  server-01:
    image: hmoragrega/grpc-server
    depends_on:
      - consul
      - kafka
    environment:
      - CONSUL_ADDRESS=consul
      - MICRO_REGISTER_TTL=10
      - MICRO_REGISTER_INTERVAL=5
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092
    networks:
      - sky-net

  server-02:
    image: hmoragrega/grpc-server
    depends_on:
      - consul
      - kafka
    environment:
      - MICRO_REGISTER_TTL=10
      - MICRO_REGISTER_INTERVAL=5
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092
    networks:
      - sky-net

  server-03:
    image: hmoragrega/grpc-server
    depends_on:
      - consul
      - kafka
    environment:
      - MICRO_REGISTER_TTL=10
      - MICRO_REGISTER_INTERVAL=5
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092
    networks:
      - sky-net

  client-01:
    image: hmoragrega/grpc-client
    depends_on:
      - consul
      - kafka
    environment:
      - MICRO_REGISTRY_ADDRESS=consul
    networks:
      - sky-net

  publisher-01:
    image: hmoragrega/grpc-publisher
    depends_on:
      - consul
      - kafka
    environment:
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_BROKER=kafka
      - MICRO_BROKER_ADDRESS=kafka:9092
    networks:
      - sky-net

  kafka:
    image: spotify/kafka
    hostname: kafka
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
      - TOPICS=events
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge
