version: '2'

services:
  consul:
    image: consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
    networks:
      - sky-net

  server-01:
    image: hmoragrega/grpc-server
    depends_on:
      - consul
    environment:
      - CONSUL_ADDRESS=consul
      - MICRO_REGISTER_TTL=10
      - MICRO_REGISTER_INTERVAL=5
      - MICRO_REGISTRY_ADDRESS=consul
    networks:
      - sky-net

  server-02:
    image: hmoragrega/grpc-server
    depends_on:
      - consul
    environment:
      - MICRO_REGISTER_TTL=10
      - MICRO_REGISTER_INTERVAL=5
      - MICRO_REGISTRY_ADDRESS=consul
    networks:
      - sky-net

  server-03:
    image: hmoragrega/grpc-server
    depends_on:
      - consul
    environment:
      - MICRO_REGISTER_TTL=10
      - MICRO_REGISTER_INTERVAL=5
      - MICRO_REGISTRY_ADDRESS=consul
    networks:
      - sky-net

  client-01:
    image: hmoragrega/grpc-client
    depends_on:
      - consul
    environment:
      - MICRO_REGISTRY_ADDRESS=consul
    networks:
      - sky-net

networks:
  sky-net:
    driver: bridge
