apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: "hmoragrega/grpc-client:latest"
          command: [
            "client",
            "--selector=static",
          ]
          imagePullPolicy: Never
          env:
          - name: MICRO_REGISTRY
            value: kubernetes
          - name: STATIC_SELECTOR_PORT_NUMBER
            value: "9090"