apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: greeter
  name: greeter
spec:
  # use NodePort here to be able to access a port on each node
  type: NodePort
  ports:
  - port: 9090
  selector:
    io.kompose.service: greeter

