apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        io.kompose.service: greeter
    spec:
      containers:
        - name: grpc-greeter
          command: [
		        "server",
            "--server_address=0.0.0.0:9090",
            "--selector=static",
	        ]
          image: "hmoragrega/grpc-server:latest"
          imagePullPolicy: Never
          ports:
          - name: grpc-port
            containerPort: 9090
          env:
          - name: MICRO_REGISTRY
            value: kubernetes
          - name: MICRO_BROKER
            value: kafka
          - name: MICRO_BROKER_ADDRESS
            value: broker:9092
        - name: health
          command: [
		        "/health",
            "--health_address=0.0.0.0:9091",
		        "--server_name=greeter",
		        "--server_address=0.0.0.0:9090"
	        ]
          image: "microhq/health:kubernetes"
          imagePullPolicy: Always
          livenessProbe:
              httpGet:
                path: /health
                port: 9091
              initialDelaySeconds: 5
              periodSeconds: 3